version: "3.2"
services:
  celery:
    build:
      context: './batch'
      dockerfile: Dockerfile
    networks:
      network:

  redis-broker:
    image: redis:latest
    ports: 
      - 6379:6379
    networks:
      network:
            
  uploader:
    build: ./uploader
    volumes:
      - ./uploader:/mnt/
    working_dir: /backend/
    command: python api_commands.py

  nginx:
    image: nginx:latest
    ports:
      - 5000:443
    volumes:
      - ./nginx/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/localhost.crt:/etc/ssl/certs/localhost.crt
      - ./nginx/localhost.key:/etc/ssl/private/localhost.key
    depends_on:
      - uploader
networks:
  network: