version: "3.2"
services:
  celery:
    build:
      context: './batch'
      dockerfile: Dockerfile
    networks:
      network:

  redis-broker:
    image: redis:latest
    ports: 
      - 6379:6379
    networks:
      network:
            
networks:
  network: