global:
  scrape_interval: 30s
  scrape_timeout: 10s

rule_files:
  - alert.yml

scrape_configs:
  - job_name: other-services
    static_configs:
    
      - targets:
          - 'prometheus:9090'
          - 'celery-exporter:9808'
  - job_name: flask-services
    scheme: https
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets:
          - 'authentication:5000'
          - 'uploader:5000'