name: development-workflow # Nombre del workflow
run-name: ${{ github.actor }} triggered this workflow
on: # ¿Cuando ejecutar?
  push: # Al hacer push a las siguientes ramas
    branches: [feature/**, bugfix/**, develop, main]

jobs:
  ci:
    name: Continuous Integration # Nombre del Job
    runs-on: ubuntu-latest # Ejecutar en Ubuntu
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint with Ruff
        run: |
          pip install ruff
          ruff --output-format=github .
        continue-on-error: false